### ISSUE TITLE
ValueError: cannot match existing table structure for [missing_date_PV_localtime] on appending data

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/pvoutput_downloader#1]
```
append_missing_date(
    date_to_load=date(2019, 1, 1), 
    datetime_of_api_request=pd.Timestamp.now(),
    system_id=system_id)

~/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py in create_axes(self, axes, obj, validate, nan_rep, data_columns, min_itemsize, **kwargs)
   3639                         "on appending data".format(
   3640                             items=(','.join(pprint_thing(item) for
-> 3641                                             item in items))))
   3642             blocks = new_blocks
   3643             blk_items = new_blk_items

ValueError: cannot match existing table structure for [missing_date_PV_localtime] on appending data
```

**Comment by JackKelly** [comment]
```
2019-08-06 16:03:03,553 - pv_output - INFO - ****************************
2019-08-06 16:03:03,554 - pv_output - INFO - system_id 5531: 352 of 829 (42%) 
2019-08-06 16:03:03,557 - pv_output - INFO - system_id 5531: 0 days already downloaded.
2019-08-06 16:03:03,563 - pv_output - INFO - system_id 5531: 0 missing dates already found: 
2019-08-06 16:03:03,564 - pv_output - INFO - system_id 5531: Will download 182 days: from 2019-01-01 to 2019-07-01
2019-08-06 16:03:03,564 - pv_output - INFO - system_id 5531: Requesting system status for 2019-01-01 (API request number 569)
2019-08-06 16:03:03,564 - pv_output - DEBUG - api_url=https://pvoutput.org/service/r2/getstatus.jsp?d=20190101&h=1&limit=288&ext=0&sid1=5531; headers={'X-Pvoutput-Apikey': '3f784ff6cfa27c44436f88da0c429b410687ad14', 'X-Pvoutput-SystemId': '68732', 'X-Rate-Limit': '1'}; service=getstatus; api_params={'d': '20190101', 'h': 1, 'limit': 288, 'ext': 0, 'sid1': 5531}; retries=150
2019-08-06 16:03:04,838 - pv_output - INFO - system_id 5531: No status found for 2019-01-01.
2019-08-06 16:03:04,862 - pv_output - ERROR - system_id 5531: Exception!
Traceback (most recent call last):
  File "<ipython-input-110-ef2470b1fc48>", line 59, in <module>
    timeseries = get_pv_system_status(system_id, date_to_load_str)
  File "/home/jack/dev/python/openclimatefix/solar/pvoutput/pvoutput.py", line 230, in get_pv_system_status
    }, **kwargs)
  File "/home/jack/dev/python/openclimatefix/solar/pvoutput/pvoutput.py", line 119, in pv_output_api_query
    response_headers=response.headers)
pvoutput.NoStatusFound:  Bad status code returned: 400
 Response content: Bad request 400: No status found
 Response headers: {'Date': 'Tue, 06 Aug 2019 15:03:04 GMT', 'Set-Cookie': 'JSESSIONID=kjtv2dndolm71r0tkl3g5bv6b;Path=/', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'X-Rate-Limit-Remaining': '294', 'X-Rate-Limit-Limit': '300', 'X-Rate-Limit-Reset': '1565107200', 'Content-Type': 'text/plain;charset=ISO-8859-1', 'Connection': 'close', 'Server': 'Jetty(7.6.17.v20150415)', 'Strict-Transport-Security': 'max-age=15768000'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 3633, in create_axes
    b, b_items = by_items.pop(items)
KeyError: ('missing_date_PV_localtime',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-110-ef2470b1fc48>", line 62, in <module>
    append_missing_date(date_to_load, datetime_of_api_request, system_id)
  File "<ipython-input-103-da4609093d14>", line 10, in append_missing_date
    store.append(key='missing_dates', value=new_missing_date)
  File "/home/jack/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 986, in append
    **kwargs)
  File "/home/jack/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 1415, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)
  File "/home/jack/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 4017, in write
    **kwargs)
  File "/home/jack/anaconda3/lib/python3.7/site-packages/pandas/io/pytables.py", line 3641, in create_axes
    item in items))))
ValueError: cannot match existing table structure for [missing_date_PV_localtime] on appending data
```
